name: libcontinual-env 
channels:
  - pytorch        
  - conda-forge    
  - defaults        
dependencies:
  - python=3.8       
  # Conda 包及其精确版本
  - numpy=1.21.5
  - pandas=1.1.5
  - pillow=9.2.0    
  - pyyaml=6.0.1    
  - scikit-learn=1.0.2
  - pytorch=1.12.1  
  - torchvision=0.13.1
  - tqdm=4.64.1

  - pip:
      - diffdist==0.1 
