device_ids: 'auto' # determine GPU ids in bus order, auto for automatic select gpu, or number to specify device
n_gpu: 1 # select the number of gpus to use
seed: 1993 # random seed for numpy, torch and cuda
deterministic: True # option for torch.backends.cudnn.benchmark and torch.backends.cudnn.deterministic