epoch: 50

batch_size: 64
val_per_epoch: 1

buffer: # By default Buffer is not used, set buffer_size to 0
  name: LinearBuffer
  kwargs:
    buffer_size: 0
    batch_size: 128
    strategy: herding # random, equal_random, reservoir, herding