init_cls_num: &init_cls_num 5
inc_cls_num: &inc_cls_num 5
total_cls_num: &total_cls_num 100
task_num: &task_num 20

task_num: *task_num
init_cls_num: *init_cls_num
inc_cls_num: *inc_cls_num
total_cls_num: *total_cls_num
epoch: 200
batch_size: 64 
val_per_epoch: 200

setting: task-aware # task-aware
seed: 2
testing_times: 1 # Don't set too high, it will take eternity

optimizer:
  name: SGD
  kwargs:
    lr: 0.01

lr_scheduler:
  name: PatienceSchedule
  kwargs:
    patience: 6
    factor: 2
    stopping_lr: 1e-5

backbone:
  name: AlexNet_API
  kwargs:

classifier:
  name: API
  kwargs:
    init_cls_num: *init_cls_num
    inc_cls_num: *inc_cls_num
    task_num: *task_num
