includes:
  - headers/data.yaml
  - headers/device.yaml
  - headers/model.yaml
  - headers/optimizer.yaml
  - backbones/resnet12.yaml

image_size: 32
  
save_path: ./
# data
init_cls_num: 10
inc_cls_num: 10
task_num: 10

# init_epoch can be none
init_epoch: 170 #200
epoch: 170 #170
device_ids: 2
n_gpu: 1
val_per_epoch: 170

batch_size: 128

optimizer:
  name: SGD
  kwargs:
    momentum: 0.9
    lr: 0.1
    weight_decay: 2e-4

lr_scheduler:
  name: MultiStepLR
  kwargs:
    gamma: 0.1
    milestones: [70, 100, 150]

backbone:
  name: resnet18
  kwargs:
    num_classes: 10
    args: 
      dataset: cifar100


buffer:
  name: LinearBuffer
  kwargs:
    buffer_size: 0 # 2000
    batch_size: 32
    strategy: random     # random, equal_random, reservoir, herding

classifier:
  name: DER
  kwargs:
    num_class: 100
    feat_dim: 512
    init_cls_num: 10
    inc_cls_num: 10
