save_path : ""
data_root: "../../../data/cifar/cifar100" #data path, where is your data

init_cls_num: &init_cls_num 10 # 第一次任务的分类数量
inc_cls_num: &inc_cls_num 10   # 之后每次任务的分类数量
num_classes: &num_classes 100 
task_num: &task_num 10

task_num: *task_num
init_cls_num: *init_cls_num
inc_cls_num: *inc_cls_num
init_epoch: 20 # 20
epoch: 20 # 20
batch_size: 128
val_per_epoch: 20
workers: 16

device_ids: 0

optimizer:
  name: Adam
  kwargs:
    lr: 0.0005
    weight_decay: 0.0


lr_scheduler:
  name: StepLR
  kwargs:
    gamma: 0.5
    step_size: 10

# buffer is not used in this method
buffer:
  name: LinearBuffer
  kwargs:
    buffer_size: 0
    strategy: None
    batch_size: 

backbone:
  name: vit_pt_imnet
  kwargs:
    # num_heads: 12
    num_classes: *num_classes
    pretrain: True
    attention: Attention_InfLoRA

classifier:
  name: InfLoRA
  kwargs:
    init_cls_num: *init_cls_num
    inc_cls_num: *inc_cls_num
    task_num: *task_num
    embd_dim: 768
    lame: 1.0
    lamb: 0.95
    rank: 10
