# Dataset ImageNet-R
dataset: &dataset "imagenet-r"
data_root: "/data/lqx/imagenet-r/"
init_cls_num: &init_cls_num 20
inc_cls_num: &inc_cls_num 20
task_num: &task_num 10
epoch: &epoch 30
image_size: &image_size 224

image_size: *image_size
dataset: *dataset
task_num: *task_num
init_cls_num: *init_cls_num
inc_cls_num: *inc_cls_num
epoch: *epoch
val_per_epoch: *epoch
workers: 24

batch_size: 128
testing_times: 1

setting: task-agnostic

optimizer:
  name: Adam
  kwargs:
    lr: 0.0005
    weight_decay: 0.
    betas: [0.9, 0.999]

lr_scheduler:
  name: CosineSchedule # CosineAnnealingLR
  kwargs:
    # T_max: *epoch
    K: *epoch

backbone:
  name: vit_pt_imnet
  kwargs:
    pretrained: True
    model_name : vit_base_patch16_224_in21k
    attn_layer: MultiHeadAttention_MultiMaskedLoRA3
    block_layer: ResidualAttentionBiBlock # Bi
    transformer_layer: Transformer_Proj
    lora_rank: 10

classifier:
  name: MInfLoRA3
  kwargs:
    dataset: *dataset
    init_cls_num: *init_cls_num
    inc_cls_num: *inc_cls_num
    task_num: *task_num
    lame: 1.0
    lamb: 0.95
    embd_dim: 768
    use_ca: False
    eval_mat: False