save_path : "" # log file placing

# Dataset ImageNet-R
dataset: &dataset "imagenet-r"
data_root: "/home/lvqiexuan/temp_data/imagenet-r/"
init_cls_num: &init_cls_num 20
inc_cls_num: &inc_cls_num 20
task_num: &task_num 10
epoch: &epoch 1 # 50

dataset: *dataset
task_num: *task_num
init_cls_num: *init_cls_num
inc_cls_num: *inc_cls_num
epoch: *epoch
val_per_epoch: *epoch
workers: 24

batch_size: 128

setting: task-aware

optimizer:
  name: SGD
  kwargs:
    lr: 0.001
    momentum: 0.9
    weight_decay: 0.0

lr_scheduler:
  name: CosineAnnealingLR
  kwargs:
    T_max: *epoch

backbone:
  name: vit_pt_imnet
  kwargs:
    pretrained: True
    model_name : vit_base_patch16_224_in21k
    attn_layer: MultiHeadAttention_MaskedLoRA
    lora_rank: 10

classifier:
  name: MInfLoRA
  kwargs:
    dataset: *dataset
    init_cls_num: *init_cls_num
    inc_cls_num: *inc_cls_num
    task_num: *task_num
    lame: 1.0
    lamb: 0.95
    embd_dim: 768
    use_ca: False
