init_cls_num: &init_cls_num 100
inc_cls_num: &inc_cls_num 20
total_cls_num: &total_cls_num 200
task_num: &task_num 6
image_size: &image_size 224

dataset: tiny-imagenet
data_root: /home/lvqiexuan/temp_data/
class_order: [131, 181, 22, 172, 144, 92, 97, 187, 58, 93, 6, 70, 106, 68, 
              153, 168, 179, 199, 29, 46, 9, 142, 134, 88, 193, 110, 26, 
              32, 117, 112, 17, 39, 166, 13, 94, 138, 109, 147, 51, 101, 
              59, 188, 116, 5, 170, 99, 100, 167, 180, 146, 65, 1, 104, 
              43, 38, 184, 123, 171, 137, 162, 71, 44, 95, 174, 12, 7, 
              54, 152, 21, 47, 28, 176, 34, 2, 132, 118, 42, 189, 150, 
              14, 165, 41, 192, 45, 82, 128, 63, 57, 197, 160, 53, 75, 
              108, 135, 121, 159, 183, 67, 169, 50, 87, 69, 89, 196, 
              115, 19, 148, 96, 86, 11, 8, 60, 33, 173, 78, 4, 119, 105, 
              182, 127, 177, 30, 186, 40, 49, 178, 76, 157, 161, 73, 164, 
              151, 31, 74, 191, 27, 125, 198, 81, 20, 155, 114, 139, 36, 
              61, 56, 145, 48, 16, 83, 62, 85, 126, 0, 102, 23, 3, 140, 
              15, 195, 133, 113, 190, 141, 52, 163, 156, 80, 111, 90, 175, 
              143, 120, 84, 18, 25, 79, 37, 154, 136, 64, 158, 24, 185, 
              72, 35, 129, 55, 149, 91, 122, 77, 103, 124, 130, 66, 10, 107, 194, 98]

task_num: *task_num
init_cls_num: *init_cls_num
inc_cls_num: *inc_cls_num
total_cls_num: *total_cls_num
epoch: 1
val_per_epoch: 1

train_batch_size: 64
test_batch_size: 64

testing_times: 1

setting: task-agnostic 

train_trfms:
  - RandomResizedCrop :
      size: *image_size
      scale: [0.9, 1.0]
      interpolation: BICUBIC
  - _convert_to_rgb: {}
  - ToTensor: {}
  - Normalize:
      mean: [0.48145466, 0.4578275, 0.40821073]
      std: [0.26862954, 0.26130258, 0.27577711]

test_trfms: 
  - RandomResizedCrop :
      size: *image_size
      scale: [0.9, 1.0]
      interpolation: BICUBIC
  - _convert_to_rgb: {}
  - ToTensor: {}
  - Normalize:
      mean: [0.48145466, 0.4578275, 0.40821073]
      std: [0.26862954, 0.26130258, 0.27577711]

optimizer:
  name: AdamW
  kwargs:
    lr: 1e-3
    weight_decay: 0.

lr_scheduler:
  name: CosineAnnealingWarmUp
  kwargs:
    T_max: 0 # Will be replaced in trainter.py with epoch * len(dataloader)
    warmup_length: 30

backbone:
  name: clip
  kwargs:
    model_name : ViT-B/16
    pretrained : True
    block_layer: ResidualAttentionBlock_MoE_MLP
    experts_num: 2
    step: 1
    top_k : 2
    act_layer: QuickGELU
    norm_layer: LayerNorm

classifier:
  name: MOE_ADAPTER4CL
  kwargs:
    init_cls_num: *init_cls_num
    inc_cls_num: *inc_cls_num
    task_num: *task_num
    embd_dim: 768
    prompt_template : "a bad photo of a {}."
    label_smoothing: 0.
