init_cls_num: &init_cls_num 20
inc_cls_num: &inc_cls_num 20
total_cls_num: &total_cls_num 100
task_num: &task_num 5
image_size: &image_size 224

task_num: *task_num
init_cls_num: *init_cls_num
inc_cls_num: *inc_cls_num
total_cls_num: *total_cls_num
init_epoch: 20 # 20
epoch: 1 # 1
batch_size: 48 # 128
val_per_epoch: 20

train_trfms:
  - RandomResizedCrop:
      size: *image_size
      scale: [0.05, 1.0]
      ratio: [0.75, 1.33333333] # [3./4., 4./3.]
  - RandomHorizontalFlip: 
      p: 0.5 
  - ToTensor: {}

test_trfms: 
  - Resize:
      size: *image_size
      interpolation: BICUBIC
  - CenterCrop:
      size: *image_size
  - ToTensor: {}

optimizer:
  name: AdamW
  kwargs:
    lr: 1e-3
    weight_decay: 0.

lr_scheduler:
  name: CosineAnnealingWarmUp
  kwargs:
    T_max: 0 # Will be replaced in trainter.py with epoch * len(dataloader)
    warmup_length: 30

backbone:
  name: clip
  kwargs:
    model_name : ViT-B/16
    pretrained : True
    block_layer: ResidualAttentionBlock_MoE_MLP
    experts_num: 1
    step: -1 # think again
    act_layer: QuickGELU
    norm_layer: LayerNorm

classifier:
  name: RanPAC
  kwargs:
    use_RP: True
    M: 10000
    first_session_training: True
    init_cls_num: *init_cls_num
    inc_cls_num: *inc_cls_num
    task_num: *task_num
    total_cls_num: *total_cls_num
    prompt_template : "a bad photo of a {}."
