includes:
  - headers/data.yaml
  - headers/device.yaml
  - headers/model.yaml
  # - headers/optimizer.yaml
  - backbones/resnet12.yaml

data_root: /data/fanzhichen/continual/cifar100
image_size: 32


save_path: ./
# data
init_cls_num: 20
inc_cls_num: 20
task_num: 5


epoch: 0 # 160
device_ids: 4
n_gpu: 1
val_per_epoch: 1


batch_size: 128


optimizer:
  name: SGD
  kwargs:
    lr: 0.03
    momentum: 0.9
    weight_decay: 0.0005

lr_scheduler:
  name: MultiStepLR
  kwargs:
    gamma: 0.1
    milestones: [60, 120, 170]

backbone:
  name: resnet18
  kwargs:
    num_classes: 100
    args: 
      dataset: cifar100


buffer:
  name: LinearBuffer
  kwargs:
    buffer_size: 1000
    batch_size: 128
    strategy: herding     # random, equal_random, reservoir, herding

classifier:
  name: TAM
  kwargs:
    num_class: 100
    feat_dim: 512
    init_cls_num: 20
    inc_cls_num: 20
    lamda: 1000
    reg_weight: 0.1
    ema_update_freq: 0.05
    ema_alpha: 0.999
    pairwise_weight: 0.1
    alpha: 0.2
    beta: 0.5
    code_dims: 64