from .finetune import Finetune
from .icarl import ICarl
from .lucir import LUCIR
from .lwf import LWF
from .wa import WA
from .bic import bic
from .ewc import EWC
from .tam import TAM
from .ocm import OCM
from .eraml import ERAML
from .erace import ERACE
from .dualprompt import DualPrompt
